//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::bus::Entity as Bus;
pub use super::bus_driver::Entity as BusDriver;
pub use super::route_node::Entity as RouteNode;
pub use super::station::Entity as Station;
pub use super::ticket::Entity as Ticket;
pub use super::user::Entity as User;
