//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ticket")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub number_of_commuters: i32,
    pub number_of_discounted_commuters: i32,
    #[sea_orm(column_type = "Double")]
    pub total_amount: f64,
    pub payment_method: String,
    pub bus_id: i32,
    pub driver_id: i32,
    pub origin_station_id: i32,
    pub destination_station_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bus::Entity",
        from = "Column::BusId",
        to = "super::bus::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bus,
    #[sea_orm(
        belongs_to = "super::bus_driver::Entity",
        from = "Column::DriverId",
        to = "super::bus_driver::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BusDriver,
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::DestinationStationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Station2,
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::OriginStationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Station1,
}

impl Related<super::bus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bus.def()
    }
}

impl Related<super::bus_driver::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BusDriver.def()
    }
}
